FilterHouses:
    path: /filter
    controller: App\Infrastructure\Controller\House\FilterHouseController:__invoke
    methods: [POST]

ListHouseById:
    path: /{id}
    controller: App\Infrastructure\Controller\House\ListHouseByIdController:__invoke
    methods: [GET]

ListHousesByOwner:
    path: /houses
    controller: App\Infrastructure\Controller\House\ListHouseByOwnerController:__invoke
    methods: [POST]

ListHouseBiddedByUser:
    path: /biddedhouses
    controller: App\Infrastructure\Controller\House\ListHouseBiddedByUserController:__invoke
    methods: [POST]

ModifyHouseWithOwnerAndId:
    path: /modify
    controller: App\Infrastructure\Controller\House\ModifyHouseWithOwnerAndIdController:__invoke
    methods: [POST]

CreateHouse:
    path: /create
    controller: App\Infrastructure\Controller\House\CreateHouseController:__invoke
    methods: [POST]
