#ListHouses:
#    path: /
#    controller: App\Infrastructure\Controller\User\ListUsersController:__invoke
#

#ListUserByDni:
#    path: /{dni}
#    controller: App\Infrastructure\Controller\User\ListUserByDniController:__invoke
#    methods: [GET]
#

#LogInUser:
#    path: /login
#    controller: App\Infrastructure\Controller\User\LogInUserController:__invoke
#    methods: [POST]
#

#RegisterUser:
#    path: /register
#    controller: App\Infrastructure\Controller\User\RegisterUserController:__invoke
#    methods: [POST]

#ListHouseBiddedByUser:
#    path: /{dni}
#    controller: App\Infrastructure\Controller\User\ListUserByDniController:__invoke
#    methods: [GET]