#ListHouses:
#    path: /
#    controller: App\Infrastructure\Controller\User\ListUsersController:__invoke
#

ListHouseById:
    path: /{id}
    controller: App\Infrastructure\Controller\House\ListHouseByIdController:__invoke
    methods: [GET]


ListHousesByOwner:
    path: /{dni}/houses
    controller: App\Infrastructure\Controller\House\ListHouseByOwnerController:__invoke
    methods: [GET]

ListHouseBiddedByUser:
    path: /{dni}/biddedhouses
    controller: App\Infrastructure\Controller\House\ListHouseBiddedByUserController:__invoke
    methods: [GET]

ModifyHouseWithOwnerAndId:
    path: /modify
    controller: App\Infrastructure\Controller\House\ModifyHouseWithOwnerAndIdController:__invoke
    methods: [POST]

CreateHouse:
    path: /create
    controller: App\Infrastructure\Controller\House\CreateHouseController:__invoke
    methods: [POST]
