ListBids:
    path: /listbids
    controller: App\Infrastructure\Controller\Bid\ListBidsController:__invoke
    methods: [GET]

AcceptBid:
    path: /acceptbid
    controller: App\Infrastructure\Controller\Bid\AcceptBidController:__invoke
    methods: [POST]

RejectBid:
    path: /rejectbid
    controller: App\Infrastructure\Controller\Bid\RejectBidController:__invoke
    methods: [POST]

ListBidByOwner:
    path: /{dni}/bids
    controller: App\Infrastructure\Controller\Bid\ListBidsByOwnerController:__invoke
    methods: [GET]

ListBidById:
    path: /{id}
    controller: App\Infrastructure\Controller\Bid\ListByIdController:__invoke
    methods: [GET]

CreateBidController:
    path: /{dni}/{house}/new/{money}
    controller: App\Infrastructure\Controller\Bid\CreateBidController:__invoke
    methods: [GET]

ModifyBidController:
    path: /{dni}/{house}/modify/{money}
    controller: App\Infrastructure\Controller\Bid\ModifyBidController:__invoke
    methods: [GET]

