ListUsers:
    path: /
    controller: App\Infrastructure\Controller\User\ListUsersController:__invoke

ListUserByDni:
    path: /user
    controller: App\Infrastructure\Controller\User\ListUserByDniController:__invoke
    methods: [POST]

LogInUser:
    path: /login
    controller: App\Infrastructure\Controller\User\LogInUserController:__invoke
    methods: [POST]

RegisterUser:
    path: /register
    controller: App\Infrastructure\Controller\User\RegisterUserController:__invoke
    methods: [POST]

UpdateUser:
    path: /update
    controller: App\Infrastructure\Controller\User\UpdateUserController:__invoke
    methods: [POST]